version: "3"

services:
  receptacle-consul:
    command: agent -server -bootstrap -rejoin -bind 0.0.0.0 -client 0.0.0.0 -ui
    image: consul:latest
    hostname: "registry"
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  receptacle-agent:
    command: --registry_address=receptacle-consul:8500
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - CONSUL_ADDR=receptacle-consul:8500
    links:
      - receptacle-consul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  receptacle-registrator:
    command: consul://localhost:8500
    image: gliderlabs/registrator:latest
    links:
      - receptacle-consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock