// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/proto/tasks.proto

/*
Package tasks is a generated protocol buffer package.

It is generated from these files:
	server/proto/tasks.proto

It has these top-level messages:
	Resources
	DeployRequest
	DeployResponse
*/
package tasks

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Resources struct {
	Memory    string   `protobuf:"bytes,1,opt,name=memory" json:"memory,omitempty"`
	CPU       string   `protobuf:"bytes,2,opt,name=CPU" json:"CPU,omitempty"`
	Instances int32    `protobuf:"varint,3,opt,name=instances" json:"instances,omitempty"`
	Volumes   []string `protobuf:"bytes,4,rep,name=volumes" json:"volumes,omitempty"`
}

func (m *Resources) Reset()                    { *m = Resources{} }
func (m *Resources) String() string            { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()               {}
func (*Resources) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Resources) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *Resources) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *Resources) GetInstances() int32 {
	if m != nil {
		return m.Instances
	}
	return 0
}

func (m *Resources) GetVolumes() []string {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type DeployRequest struct {
	Name      string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Image     string     `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Command   []string   `protobuf:"bytes,3,rep,name=command" json:"command,omitempty"`
	Resources *Resources `protobuf:"bytes,4,opt,name=resources" json:"resources,omitempty"`
	Env       []string   `protobuf:"bytes,5,rep,name=env" json:"env,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeployRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *DeployRequest) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *DeployRequest) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *DeployRequest) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

type DeployResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *DeployResponse) Reset()                    { *m = DeployResponse{} }
func (m *DeployResponse) String() string            { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()               {}
func (*DeployResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeployResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Resources)(nil), "Resources")
	proto.RegisterType((*DeployRequest)(nil), "DeployRequest")
	proto.RegisterType((*DeployResponse)(nil), "DeployResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Tasks service

type TasksClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...client.CallOption) (*DeployResponse, error)
}

type tasksClient struct {
	c           client.Client
	serviceName string
}

func NewTasksClient(serviceName string, c client.Client) TasksClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "tasks"
	}
	return &tasksClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *tasksClient) Deploy(ctx context.Context, in *DeployRequest, opts ...client.CallOption) (*DeployResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Tasks.Deploy", in)
	out := new(DeployResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tasks service

type TasksHandler interface {
	Deploy(context.Context, *DeployRequest, *DeployResponse) error
}

func RegisterTasksHandler(s server.Server, hdlr TasksHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Tasks{hdlr}, opts...))
}

type Tasks struct {
	TasksHandler
}

func (h *Tasks) Deploy(ctx context.Context, in *DeployRequest, out *DeployResponse) error {
	return h.TasksHandler.Deploy(ctx, in, out)
}

func init() { proto.RegisterFile("server/proto/tasks.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xdd, 0x4a, 0xc4, 0x30,
	0x10, 0x85, 0xad, 0xfd, 0x91, 0x8e, 0xb8, 0xca, 0x20, 0x12, 0xc4, 0x8b, 0xd2, 0xab, 0x80, 0xd0,
	0x85, 0xd5, 0x37, 0xd0, 0x07, 0x90, 0xa0, 0x0f, 0x10, 0xeb, 0x20, 0x8b, 0x9b, 0xa4, 0x66, 0xd2,
	0xc2, 0x3e, 0x85, 0xaf, 0x2c, 0xe9, 0xcf, 0x2e, 0x7b, 0x77, 0xbe, 0x09, 0x73, 0x26, 0xe7, 0x80,
	0x60, 0xf2, 0x03, 0xf9, 0x75, 0xe7, 0x5d, 0x70, 0xeb, 0xa0, 0xf9, 0x87, 0x9b, 0x51, 0xd7, 0x06,
	0x4a, 0x45, 0xec, 0x7a, 0xdf, 0x12, 0xe3, 0x1d, 0x14, 0x86, 0x8c, 0xf3, 0x7b, 0x91, 0x54, 0x89,
	0x2c, 0xd5, 0x4c, 0x78, 0x03, 0xe9, 0xcb, 0xdb, 0x87, 0x38, 0x1f, 0x87, 0x51, 0xe2, 0x03, 0x94,
	0x5b, 0xcb, 0x41, 0xdb, 0x96, 0x58, 0xa4, 0x55, 0x22, 0x73, 0x75, 0x1c, 0xa0, 0x80, 0x8b, 0xc1,
	0xed, 0x7a, 0x43, 0x2c, 0xb2, 0x2a, 0x95, 0xa5, 0x5a, 0xb0, 0xfe, 0x4b, 0xe0, 0xea, 0x95, 0xba,
	0x9d, 0xdb, 0x2b, 0xfa, 0xed, 0x89, 0x03, 0x22, 0x64, 0x56, 0x1b, 0x9a, 0x2f, 0x8e, 0x1a, 0x6f,
	0x21, 0xdf, 0x1a, 0xfd, 0x4d, 0xf3, 0xc5, 0x09, 0xa2, 0x6b, 0xeb, 0x8c, 0xd1, 0xf6, 0x4b, 0xa4,
	0x93, 0xeb, 0x8c, 0x28, 0xa1, 0xf4, 0x4b, 0x08, 0x91, 0x55, 0x89, 0xbc, 0xdc, 0x40, 0x73, 0x88,
	0xa5, 0x8e, 0x8f, 0x31, 0x09, 0xd9, 0x41, 0xe4, 0xe3, 0x7e, 0x94, 0xb5, 0x84, 0xd5, 0xf2, 0x21,
	0xee, 0x9c, 0x65, 0x8a, 0x2d, 0x70, 0xd0, 0xa1, 0xe7, 0xa5, 0x85, 0x89, 0x36, 0xcf, 0x90, 0xbf,
	0xc7, 0xe6, 0xf0, 0x11, 0x8a, 0x69, 0x05, 0x57, 0xcd, 0x49, 0x98, 0xfb, 0xeb, 0xe6, 0xd4, 0xab,
	0x3e, 0xfb, 0x2c, 0xc6, 0x9e, 0x9f, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x84, 0x7b, 0x41, 0x5d,
	0x83, 0x01, 0x00, 0x00,
}
