// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/proto/tasks.proto

/*
Package tasks is a generated protocol buffer package.

It is generated from these files:
	server/proto/tasks.proto

It has these top-level messages:
	Resources
	DeployRequest
	DeployResponse
	UndeployRequest
	UndeployResponse
	ListRequest
	List
	ListResponse
	HostsRequest
	Host
	HostsResponse
*/
package tasks

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Resources struct {
	Memory    string   `protobuf:"bytes,1,opt,name=memory" json:"memory,omitempty"`
	CPU       float32  `protobuf:"fixed32,2,opt,name=CPU" json:"CPU,omitempty"`
	Instances int32    `protobuf:"varint,3,opt,name=instances" json:"instances,omitempty"`
	Volumes   []string `protobuf:"bytes,4,rep,name=volumes" json:"volumes,omitempty"`
}

func (m *Resources) Reset()                    { *m = Resources{} }
func (m *Resources) String() string            { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()               {}
func (*Resources) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Resources) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *Resources) GetCPU() float32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

func (m *Resources) GetInstances() int32 {
	if m != nil {
		return m.Instances
	}
	return 0
}

func (m *Resources) GetVolumes() []string {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type DeployRequest struct {
	Name      string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Image     string     `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Command   []string   `protobuf:"bytes,3,rep,name=command" json:"command,omitempty"`
	Resources *Resources `protobuf:"bytes,4,opt,name=resources" json:"resources,omitempty"`
	Env       []string   `protobuf:"bytes,5,rep,name=env" json:"env,omitempty"`
	Nodes     []string   `protobuf:"bytes,6,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeployRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *DeployRequest) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *DeployRequest) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *DeployRequest) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *DeployRequest) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type DeployResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *DeployResponse) Reset()                    { *m = DeployResponse{} }
func (m *DeployResponse) String() string            { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()               {}
func (*DeployResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeployResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UndeployRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UndeployRequest) Reset()                    { *m = UndeployRequest{} }
func (m *UndeployRequest) String() string            { return proto.CompactTextString(m) }
func (*UndeployRequest) ProtoMessage()               {}
func (*UndeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UndeployRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UndeployResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *UndeployResponse) Reset()                    { *m = UndeployResponse{} }
func (m *UndeployResponse) String() string            { return proto.CompactTextString(m) }
func (*UndeployResponse) ProtoMessage()               {}
func (*UndeployResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UndeployResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ListRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type List struct {
	Host  string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	Port  string `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	Ip    string `protobuf:"bytes,5,opt,name=ip" json:"ip,omitempty"`
}

func (m *List) Reset()                    { *m = List{} }
func (m *List) String() string            { return proto.CompactTextString(m) }
func (*List) ProtoMessage()               {}
func (*List) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *List) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *List) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *List) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *List) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *List) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ListResponse struct {
	List []*List `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListResponse) GetList() []*List {
	if m != nil {
		return m.List
	}
	return nil
}

type HostsRequest struct {
}

func (m *HostsRequest) Reset()                    { *m = HostsRequest{} }
func (m *HostsRequest) String() string            { return proto.CompactTextString(m) }
func (*HostsRequest) ProtoMessage()               {}
func (*HostsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Host struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *Host) Reset()                    { *m = Host{} }
func (m *Host) String() string            { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()               {}
func (*Host) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Host) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Host) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Host) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type HostsResponse struct {
	Hosts []*Host `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
}

func (m *HostsResponse) Reset()                    { *m = HostsResponse{} }
func (m *HostsResponse) String() string            { return proto.CompactTextString(m) }
func (*HostsResponse) ProtoMessage()               {}
func (*HostsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *HostsResponse) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func init() {
	proto.RegisterType((*Resources)(nil), "Resources")
	proto.RegisterType((*DeployRequest)(nil), "DeployRequest")
	proto.RegisterType((*DeployResponse)(nil), "DeployResponse")
	proto.RegisterType((*UndeployRequest)(nil), "UndeployRequest")
	proto.RegisterType((*UndeployResponse)(nil), "UndeployResponse")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*List)(nil), "List")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterType((*HostsRequest)(nil), "HostsRequest")
	proto.RegisterType((*Host)(nil), "Host")
	proto.RegisterType((*HostsResponse)(nil), "HostsResponse")
}

func init() { proto.RegisterFile("server/proto/tasks.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xdb, 0x8e, 0xd3, 0x30,
	0x10, 0x6d, 0x6e, 0x85, 0x4c, 0xdb, 0x6c, 0xb1, 0x10, 0x32, 0x05, 0xa4, 0xc8, 0xd2, 0x4a, 0xe6,
	0x22, 0xaf, 0x28, 0x9f, 0xc0, 0x3e, 0xf0, 0xc0, 0x03, 0xb2, 0xd8, 0x0f, 0x08, 0xb5, 0xc5, 0x46,
	0x34, 0x71, 0xc8, 0xb8, 0x95, 0xf6, 0x83, 0xf8, 0x07, 0x3e, 0x0f, 0xd9, 0x71, 0x7a, 0x13, 0xd2,
	0xbe, 0xcd, 0x99, 0x49, 0xe7, 0x9c, 0x39, 0xc7, 0x05, 0x8a, 0xba, 0xdf, 0xeb, 0xfe, 0xa6, 0xeb,
	0x8d, 0x35, 0x37, 0xb6, 0xc2, 0x5f, 0x28, 0x7c, 0xcd, 0x1a, 0xc8, 0xa5, 0x46, 0xb3, 0xeb, 0x37,
	0x1a, 0xc9, 0x0b, 0x98, 0x36, 0xba, 0x31, 0xfd, 0x03, 0x8d, 0xca, 0x88, 0xe7, 0x32, 0x20, 0xb2,
	0x84, 0xe4, 0xf3, 0xb7, 0x3b, 0x1a, 0x97, 0x11, 0x8f, 0xa5, 0x2b, 0xc9, 0x6b, 0xc8, 0xeb, 0x16,
	0x6d, 0xd5, 0x6e, 0x34, 0xd2, 0xa4, 0x8c, 0x78, 0x26, 0x8f, 0x0d, 0x42, 0xe1, 0xc9, 0xde, 0x6c,
	0x77, 0x8d, 0x46, 0x9a, 0x96, 0x09, 0xcf, 0xe5, 0x08, 0xd9, 0x9f, 0x08, 0x16, 0xb7, 0xba, 0xdb,
	0x9a, 0x07, 0xa9, 0x7f, 0xef, 0x34, 0x5a, 0x42, 0x20, 0x6d, 0xab, 0x46, 0x07, 0x46, 0x5f, 0x93,
	0xe7, 0x90, 0xd5, 0x4d, 0xf5, 0x53, 0x7b, 0xc6, 0x5c, 0x0e, 0xc0, 0x6d, 0xdd, 0x98, 0xa6, 0xa9,
	0x5a, 0x45, 0x93, 0x61, 0x6b, 0x80, 0x84, 0x43, 0xde, 0x8f, 0x47, 0xd0, 0xb4, 0x8c, 0xf8, 0x6c,
	0x0d, 0xe2, 0x70, 0x96, 0x3c, 0x0e, 0xdd, 0x25, 0xba, 0xdd, 0xd3, 0xcc, 0xff, 0xde, 0x95, 0x8e,
	0xab, 0x35, 0x4a, 0x23, 0x9d, 0xfa, 0xde, 0x00, 0x18, 0x87, 0x62, 0x94, 0x89, 0x9d, 0x69, 0x51,
	0x3b, 0x6f, 0xd0, 0x56, 0x76, 0x87, 0xa3, 0x37, 0x03, 0x62, 0xd7, 0x70, 0x75, 0xd7, 0xaa, 0xc7,
	0x4e, 0x62, 0xef, 0x60, 0x79, 0xfc, 0xec, 0x91, 0x95, 0x6f, 0x60, 0xf6, 0xb5, 0x46, 0x3b, 0xae,
	0x2b, 0x20, 0xae, 0x55, 0xf8, 0x24, 0xae, 0x15, 0xbb, 0x87, 0xd4, 0x8d, 0x1d, 0xcd, 0xbd, 0x41,
	0x3b, 0xd2, 0xb8, 0xfa, 0x40, 0x1d, 0xff, 0xcf, 0xcd, 0xe4, 0xd4, 0x4d, 0x02, 0x69, 0x67, 0x7a,
	0xeb, 0xed, 0xca, 0xa5, 0xaf, 0x3d, 0x53, 0x47, 0xb3, 0xc0, 0xd4, 0xb1, 0xb7, 0x30, 0x1f, 0x84,
	0x04, 0xc1, 0x2f, 0x21, 0xdd, 0xd6, 0x9e, 0x31, 0xe1, 0xb3, 0x75, 0x26, 0xfc, 0xd0, 0xb7, 0x58,
	0x01, 0xf3, 0x2f, 0x06, 0x2d, 0x06, 0xd1, 0xec, 0x16, 0x52, 0x87, 0x2f, 0xc5, 0x7b, 0x81, 0x46,
	0x1d, 0x05, 0x1a, 0xe5, 0x83, 0xad, 0x94, 0xea, 0x35, 0x62, 0x90, 0x38, 0x42, 0xf6, 0x01, 0x16,
	0x61, 0x6b, 0x50, 0xf0, 0x0a, 0x32, 0x77, 0x27, 0x1e, 0x24, 0xb8, 0xb1, 0x1c, 0x7a, 0xeb, 0xbf,
	0x11, 0x64, 0xdf, 0xdd, 0xdb, 0x26, 0xef, 0x61, 0x3a, 0xc4, 0x47, 0x0a, 0x71, 0xf6, 0xdc, 0x56,
	0x57, 0xe2, 0x3c, 0x57, 0x36, 0x21, 0x1f, 0xe1, 0xe9, 0x18, 0x0d, 0x59, 0x8a, 0x8b, 0x30, 0x57,
	0xcf, 0xc4, 0x65, 0x6e, 0x6c, 0x42, 0xae, 0x43, 0x04, 0x73, 0x71, 0x12, 0xd4, 0x6a, 0x21, 0x4e,
	0xdd, 0x62, 0x13, 0xc2, 0x21, 0xf3, 0xf2, 0xc9, 0x42, 0x9c, 0x9a, 0xb3, 0x2a, 0xc4, 0xd9, 0x55,
	0x6c, 0xf2, 0x63, 0xea, 0xff, 0x8d, 0x9f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x60, 0xc9, 0x6e,
	0x51, 0xa9, 0x03, 0x00, 0x00,
}
