// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/proto/tasks.proto

/*
Package tasks is a generated protocol buffer package.

It is generated from these files:
	server/proto/tasks.proto

It has these top-level messages:
	Resources
	DeployRequest
	DeployResponse
	UndeployRequest
	UndeployResponse
	ListRequest
	ListResponse
*/
package tasks

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Resources struct {
	Memory    string   `protobuf:"bytes,1,opt,name=memory" json:"memory,omitempty"`
	CPU       float32  `protobuf:"fixed32,2,opt,name=CPU" json:"CPU,omitempty"`
	Instances int32    `protobuf:"varint,3,opt,name=instances" json:"instances,omitempty"`
	Volumes   []string `protobuf:"bytes,4,rep,name=volumes" json:"volumes,omitempty"`
}

func (m *Resources) Reset()                    { *m = Resources{} }
func (m *Resources) String() string            { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()               {}
func (*Resources) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Resources) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *Resources) GetCPU() float32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

func (m *Resources) GetInstances() int32 {
	if m != nil {
		return m.Instances
	}
	return 0
}

func (m *Resources) GetVolumes() []string {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type DeployRequest struct {
	Name      string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Image     string     `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Command   []string   `protobuf:"bytes,3,rep,name=command" json:"command,omitempty"`
	Resources *Resources `protobuf:"bytes,4,opt,name=resources" json:"resources,omitempty"`
	Env       []string   `protobuf:"bytes,5,rep,name=env" json:"env,omitempty"`
	Nodes     []string   `protobuf:"bytes,6,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeployRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *DeployRequest) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *DeployRequest) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *DeployRequest) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *DeployRequest) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type DeployResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *DeployResponse) Reset()                    { *m = DeployResponse{} }
func (m *DeployResponse) String() string            { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()               {}
func (*DeployResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeployResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UndeployRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UndeployRequest) Reset()                    { *m = UndeployRequest{} }
func (m *UndeployRequest) String() string            { return proto.CompactTextString(m) }
func (*UndeployRequest) ProtoMessage()               {}
func (*UndeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UndeployRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UndeployResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *UndeployResponse) Reset()                    { *m = UndeployResponse{} }
func (m *UndeployResponse) String() string            { return proto.CompactTextString(m) }
func (*UndeployResponse) ProtoMessage()               {}
func (*UndeployResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UndeployResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ListRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListResponse struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Image     string `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Memory    string `protobuf:"bytes,3,opt,name=memory" json:"memory,omitempty"`
	CPU       string `protobuf:"bytes,4,opt,name=CPU" json:"CPU,omitempty"`
	Instances int32  `protobuf:"varint,5,opt,name=instances" json:"instances,omitempty"`
	Status    string `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ListResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ListResponse) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *ListResponse) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *ListResponse) GetInstances() int32 {
	if m != nil {
		return m.Instances
	}
	return 0
}

func (m *ListResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Resources)(nil), "Resources")
	proto.RegisterType((*DeployRequest)(nil), "DeployRequest")
	proto.RegisterType((*DeployResponse)(nil), "DeployResponse")
	proto.RegisterType((*UndeployRequest)(nil), "UndeployRequest")
	proto.RegisterType((*UndeployResponse)(nil), "UndeployResponse")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Tasks service

type TasksClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...client.CallOption) (*DeployResponse, error)
	Undeploy(ctx context.Context, in *UndeployRequest, opts ...client.CallOption) (*UndeployResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
}

type tasksClient struct {
	c           client.Client
	serviceName string
}

func NewTasksClient(serviceName string, c client.Client) TasksClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "tasks"
	}
	return &tasksClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *tasksClient) Deploy(ctx context.Context, in *DeployRequest, opts ...client.CallOption) (*DeployResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Tasks.Deploy", in)
	out := new(DeployResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksClient) Undeploy(ctx context.Context, in *UndeployRequest, opts ...client.CallOption) (*UndeployResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Tasks.Undeploy", in)
	out := new(UndeployResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Tasks.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tasks service

type TasksHandler interface {
	Deploy(context.Context, *DeployRequest, *DeployResponse) error
	Undeploy(context.Context, *UndeployRequest, *UndeployResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterTasksHandler(s server.Server, hdlr TasksHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Tasks{hdlr}, opts...))
}

type Tasks struct {
	TasksHandler
}

func (h *Tasks) Deploy(ctx context.Context, in *DeployRequest, out *DeployResponse) error {
	return h.TasksHandler.Deploy(ctx, in, out)
}

func (h *Tasks) Undeploy(ctx context.Context, in *UndeployRequest, out *UndeployResponse) error {
	return h.TasksHandler.Undeploy(ctx, in, out)
}

func (h *Tasks) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.TasksHandler.List(ctx, in, out)
}

func init() { proto.RegisterFile("server/proto/tasks.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdb, 0x4a, 0x2b, 0x31,
	0x14, 0x86, 0x9b, 0x39, 0xed, 0x3d, 0xab, 0xc7, 0x1d, 0x36, 0x12, 0x8a, 0xc2, 0x10, 0x28, 0x0c,
	0x0a, 0x29, 0xd6, 0x47, 0xd0, 0x4b, 0x2f, 0x24, 0xd8, 0x07, 0x18, 0x3b, 0x41, 0x06, 0x9b, 0xa4,
	0x4e, 0x66, 0x0a, 0x7d, 0x09, 0xaf, 0x7d, 0x01, 0xdf, 0x53, 0x32, 0x07, 0xa7, 0xad, 0x42, 0xbd,
	0x5b, 0xff, 0x4a, 0xb2, 0x0e, 0xdf, 0x1f, 0x20, 0x46, 0xe4, 0x5b, 0x91, 0xcf, 0x37, 0xb9, 0x2e,
	0xf4, 0xbc, 0x48, 0xcc, 0x8b, 0x61, 0x55, 0x4c, 0x25, 0x84, 0x5c, 0x18, 0x5d, 0xe6, 0x2b, 0x61,
	0xf0, 0x19, 0x04, 0x52, 0x48, 0x9d, 0xef, 0x08, 0x8a, 0x50, 0x1c, 0xf2, 0x46, 0xe1, 0x09, 0xb8,
	0xb7, 0x0f, 0x4b, 0xe2, 0x44, 0x28, 0x76, 0xb8, 0x0d, 0xf1, 0x39, 0x84, 0x99, 0x32, 0x45, 0xa2,
	0x56, 0xc2, 0x10, 0x37, 0x42, 0xb1, 0xcf, 0xbb, 0x04, 0x26, 0xf0, 0x67, 0xab, 0xd7, 0xa5, 0x14,
	0x86, 0x78, 0x91, 0x1b, 0x87, 0xbc, 0x95, 0xf4, 0x03, 0xc1, 0xf0, 0x4e, 0x6c, 0xd6, 0x7a, 0xc7,
	0xc5, 0x6b, 0x29, 0x4c, 0x81, 0x31, 0x78, 0x2a, 0x91, 0xa2, 0xe9, 0x58, 0xc5, 0xf8, 0x3f, 0xf8,
	0x99, 0x4c, 0x9e, 0x45, 0xd5, 0x31, 0xe4, 0xb5, 0xb0, 0x55, 0x57, 0x5a, 0xca, 0x44, 0xa5, 0xc4,
	0xad, 0xab, 0x36, 0x12, 0xc7, 0x10, 0xe6, 0xed, 0x12, 0xc4, 0x8b, 0x50, 0xdc, 0x5f, 0x00, 0xfb,
	0x5a, 0x8b, 0x77, 0x87, 0x76, 0x13, 0xa1, 0xb6, 0xc4, 0xaf, 0xde, 0xdb, 0xd0, 0xf6, 0x52, 0x3a,
	0x15, 0x86, 0x04, 0x55, 0xae, 0x16, 0x34, 0x86, 0x51, 0x3b, 0xa6, 0xd9, 0x68, 0x65, 0x84, 0x65,
	0x63, 0x8a, 0xa4, 0x28, 0x4d, 0xcb, 0xa6, 0x56, 0x74, 0x06, 0xe3, 0xa5, 0x4a, 0x4f, 0xad, 0x44,
	0x2f, 0x61, 0xd2, 0x5d, 0x3b, 0x51, 0xf2, 0x02, 0xfa, 0xf7, 0x99, 0x29, 0xda, 0x72, 0x23, 0x70,
	0xb2, 0xb4, 0xb9, 0xe2, 0x64, 0x29, 0x7d, 0x47, 0x30, 0xa8, 0xcf, 0x9b, 0x3a, 0xbf, 0x47, 0xd8,
	0x19, 0xec, 0xfe, 0x64, 0xb0, 0x57, 0x25, 0xbf, 0x1b, 0xec, 0x1f, 0x1b, 0xdc, 0x4d, 0x1e, 0xec,
	0x4f, 0xbe, 0x78, 0x43, 0xe0, 0x3f, 0xda, 0xdf, 0x85, 0xaf, 0x20, 0xa8, 0x01, 0xe2, 0x11, 0x3b,
	0x30, 0x7c, 0x3a, 0x66, 0x87, 0x64, 0x69, 0x0f, 0x5f, 0xc3, 0xdf, 0x16, 0x0e, 0x9e, 0xb0, 0x23,
	0x9c, 0xd3, 0x7f, 0xec, 0x98, 0x1c, 0xed, 0xe1, 0x19, 0x78, 0x96, 0x01, 0x1e, 0xb0, 0x3d, 0x54,
	0xd3, 0x21, 0xdb, 0x07, 0x43, 0x7b, 0x4f, 0x41, 0xf5, 0xcb, 0x6f, 0x3e, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xb7, 0xcd, 0x37, 0xdb, 0x01, 0x03, 0x00, 0x00,
}
